name: Rebuild on Upstream Update

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 6 * * *' # Runs daily at 6am UTC
  workflow_dispatch:
    inputs:
      rebuild_tag:
        description: 'Tag to rebuild (optional, overrides auto-detect)'
        required: false
        default: ''

jobs:
  check-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get latest upstream tag
        id: get_tag
        run: |
          if [ -n "${{ github.event.inputs.rebuild_tag }}" ]; then
            echo "tag=${{ github.event.inputs.rebuild_tag }}" >> $GITHUB_OUTPUT
          else
            latest_tag=$(curl -s "https://registry.hub.docker.com/v2/repositories/bluenviron/mediamtx/tags?page_size=100" | jq -r '.results[].name' | grep -E '^v?[0-9]+(\.[0-9]+)*$' | grep -v '-' | sort -V | tail -n1)
            echo "tag=$latest_tag" >> $GITHUB_OUTPUT
          fi

      - name: Read last built tag
        id: last_tag
        run: |
          echo "LAST_TAG=$(cat .last_built_tag 2>/dev/null || echo 'none')" >> $GITHUB_ENV

      - name: Compare tags
        id: compare
        run: |
          if [ -n "${{ github.event.inputs.rebuild_tag }}" ]; then
            echo "new_tag=true" >> $GITHUB_OUTPUT
          elif [ "${{ steps.get_tag.outputs.tag }}" != "${{ env.LAST_TAG }}" ]; then
            echo "new_tag=true" >> $GITHUB_OUTPUT
          else
            echo "new_tag=false" >> $GITHUB_OUTPUT
          fi

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        if: steps.compare.outputs.new_tag == 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/mediamtx:${{ steps.get_tag.outputs.tag }}-ffmpeg
          build-args: |
            VERSION_TAG=${{ steps.get_tag.outputs.tag }}-ffmpeg
          platforms: linux/amd64,linux/arm64

      - name: Update last built tag
        if: steps.compare.outputs.new_tag == 'true'
        run: echo "${{ steps.get_tag.outputs.tag }}" > .last_built_tag

      - name: Commit and push .last_built_tag
        if: steps.compare.outputs.new_tag == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update last built tag
          file_pattern: .last_built_tag
